# CMake generated Testfile for 
# Source directory: /Users/alexarse/Project/axLib/libs/lpng1610
# Build directory: /Users/alexarse/Project/axLib/libs/lpng1610
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pngtest "./pngtest" "/Users/alexarse/Project/axLib/libs/lpng1610/pngtest.png")
add_test(pngvalid "./pngvalid")
add_test(pngstest "./pngstest" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn0g01.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn0g02.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn0g04.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn0g08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn0g16.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn2c08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn2c16.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn3p01.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn3p02.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn3p04.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn3p08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn4a08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn4a16.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn6a08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/basn6a16.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbbn0g01.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbbn0g02.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbbn0g04.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbbn2c16.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbbn3p08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbgn2c16.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbgn3p08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbrn2c08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbwn0g16.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbwn3p08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftbyn3p08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftp0n0g08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftp0n2c08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftp0n3p08.png" "/Users/alexarse/Project/axLib/libs/lpng1610/contrib/pngsuite/ftp1n3p08.png")
